name: CD
on:
  push:
    branches:
      - main
      - backport/*.*
    paths:
      - spack.yaml
jobs:
  cd:
    name: CD
    uses: access-nri/build-cd/.github/workflows/cd.yml@404-merge-config-into-manifest
    with:
      model: ${{ vars.NAME }}
      spack-manifest-schema-version: 3-0-0
    permissions:
      contents: write
      pull-requests: write
    secrets: inherit
